"""Pre-seed Hyperspell collections team-ui + team-devops.

Mirrors the Slack messages we just seeded into #ui and #devops, plus a synthetic
Notion ADR per team. Once you share the real Notion `TeamHQ` page with the
NIA_HACK integration, run hyperspell_seed_notion.py to swap the synthetic
ADRs out for live Notion-sourced ones.
"""
from __future__ import annotations

import os
import sys
from pathlib import Path

env = Path(__file__).resolve().parent.parent / ".env"
if env.exists():
    for line in env.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        k, v = line.split("=", 1)
        os.environ.setdefault(k.strip(), v.strip())

# Make the agent package importable from scripts/
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from agent.hyperspell import add_memory  # noqa: E402


UI_BRAIN = [
    ("#ui Slack — TS api-client is auto-generated",
     "Reminder team: our TS api-client is autogenerated from the FastAPI OpenAPI "
     "schema. If backend changes the schema shape, we regen. Don't hand-edit "
     "/frontend/src/api-client.ts.",
     "slack"),
    ("#ui Slack — Alice on jest coverage",
     "We run jest in CI on every PR. Coverage threshold is 80% for "
     "/frontend/src/api-client. Don't drop it without a chat.",
     "slack"),
    ("#ui Slack — OpenAPI shape sign-off",
     "Heads up: any change that breaks the OpenAPI shape (snake_case→camelCase, "
     "removing fields, etc.) needs a UI sign-off. Past spec drift cost us a release in Q3.",
     "slack"),
    ("#ui Slack — react-query standard",
     "We standardized on react-query for data fetching. Don't introduce SWR or "
     "fetch-only patterns; we audited and removed them in PR #412.",
     "slack"),
    ("#ui Slack — SSE streaming wrapper",
     "If backend ships SSE, we use the 'react-event-source' wrapper from "
     "/frontend/src/lib. Don't roll your own.",
     "slack"),
    ("ADR-18 Frontend API client conventions",
     "Status: Accepted (2024-09-02). Owner: Alice (UI lead).\n\n"
     "Decisions:\n"
     "  1. /frontend/src/api-client.ts is generated by openapi-typescript-codegen "
     "from the live FastAPI OpenAPI schema. Hand-edits are forbidden.\n"
     "  2. UI ships 80% jest coverage minimum on api-client and its hooks.\n"
     "  3. Schema shape changes (camelCase, field rename, removal) require UI "
     "sign-off before merge — see #ui Slack discussion Mar 2024.\n"
     "  4. Data-fetching: react-query only. SWR/raw-fetch removed in PR #412.\n"
     "  5. SSE/streaming: use the in-house 'react-event-source' wrapper.\n",
     "adr"),
]

DEVOPS_BRAIN = [
    ("#devops Slack — Grace on Dockerfile base",
     "Dockerfile is multi-stage, slim base. Don't switch to alpine without "
     "testing — we hit DNS issues in our k8s last quarter.",
     "slack"),
    ("#devops Slack — deploy script binary path",
     "deploy.sh assumes the binary is at /app/server. If we port FastAPI to "
     "a Go binary, deploy script needs path + healthcheck updates. Coordinate w/ #backend.",
     "slack"),
    ("#devops Slack — SLO budget",
     "SLO budget: p99 latency 250ms. Any change touching request hot path "
     "needs benchmark numbers in the PR before merge. No 'I think it's fine' allowed.",
     "slack"),
    ("#devops Slack — k8s resource limits",
     "k8s manifests live in /src/infra/k8s. Resource limits set conservatively "
     "(128 Mi req, 512 Mi limit). Don't bump without justification — we've been "
     "burned by overcommit.",
     "slack"),
    ("#devops Slack — image size budget",
     "Image size budget: 250 MB. Current FastAPI build is 220 MB. If we move to "
     "Go, target should be <80 MB — that's the cost case for the rewrite.",
     "slack"),
    ("ADR-21 Deployment policy",
     "Status: Accepted (2024-11-15). Owner: Grace (DevOps lead).\n\n"
     "Decisions:\n"
     "  1. Dockerfile must be multi-stage, slim Debian base. No alpine — DNS issues in our k8s.\n"
     "  2. Production binary path is /app/server. Deploy script + healthcheck assume this.\n"
     "  3. p99 latency SLO: 250ms. Hot-path PRs require benchmark numbers.\n"
     "  4. k8s pod limits: 128 Mi request, 512 Mi limit. Bumps require justification.\n"
     "  5. Image size budget: 250 MB. Go rewrite target: <80 MB.\n",
     "adr"),
]

DS_EXTRA = [
    ("ADR-15 Embedding pipeline standards",
     "Status: Accepted (2024-07-10). Owner: Iris (DS lead).\n\n"
     "Decisions:\n"
     "  1. Streaming completions required for embeddings pipeline (4x batch perf).\n"
     "  2. Sklearn-compatible interface for ML calls. No direct openai imports in pipelines.\n"
     "  3. Never call sync OpenAI API in batch jobs — see incident INC-203.\n"
     "  4. Pin OpenAI model versions explicitly. Auto-bump breaks experiment reproducibility.\n",
     "adr"),
]


def main() -> int:
    seeded = 0
    for team, items in (("ui", UI_BRAIN), ("devops", DEVOPS_BRAIN), ("ds", DS_EXTRA)):
        for title, text, kind in items:
            r = add_memory(team=team, title=title, text=text, kind=kind)
            print(f"  team-{team:7s} {kind:5s}  {r['resource_id']}  {title[:60]}")
            seeded += 1
    print()
    print(f"OK: seeded {seeded} memories")
    return 0


if __name__ == "__main__":
    sys.exit(main())
