"""Create real Notion ADR pages under the `teamHQ` parent via Notion REST.

Uses the integration token (NOTION_TOKEN). Idempotent: skips pages whose
title already exists under the parent.

After this runs, we get 4 real Notion URLs to cite from agent decisions:
  - ADR-12 OpenAI client conventions (Backend)
  - ADR-15 Embedding pipeline standards (DS)
  - ADR-18 Frontend API client conventions (UI)
  - ADR-21 Deployment policy (DevOps)
"""
from __future__ import annotations

import json
import os
import sys
import time
import urllib.error
import urllib.request
from pathlib import Path

env = Path(__file__).resolve().parent.parent / ".env"
for line in env.read_text().splitlines():
    line = line.strip()
    if not line or line.startswith("#") or "=" not in line:
        continue
    k, v = line.split("=", 1)
    os.environ.setdefault(k.strip(), v.strip())

TOKEN = os.environ["NOTION_TOKEN"]
PARENT_ID = "35b37816-eeb5-8008-8dc9-f5b7b4f40313"  # teamHQ page

NV = "2022-06-28"


def notion(method: str, path: str, body: dict | None = None) -> dict:
    data = json.dumps(body).encode() if body is not None else None
    req = urllib.request.Request(
        "https://api.notion.com/v1" + path,
        data=data,
        headers={
            "Authorization": f"Bearer {TOKEN}",
            "Notion-Version": NV,
            "Content-Type": "application/json",
        },
        method=method,
    )
    try:
        with urllib.request.urlopen(req, timeout=30) as resp:
            return json.loads(resp.read())
    except urllib.error.HTTPError as e:
        return {"error": e.code, "body": e.read().decode()[:500]}


def para(text: str) -> dict:
    return {
        "object": "block",
        "type": "paragraph",
        "paragraph": {"rich_text": [{"type": "text", "text": {"content": text}}]},
    }


def bullet(text: str) -> dict:
    return {
        "object": "block",
        "type": "bulleted_list_item",
        "bulleted_list_item": {"rich_text": [{"type": "text", "text": {"content": text}}]},
    }


def h2(text: str) -> dict:
    return {
        "object": "block",
        "type": "heading_2",
        "heading_2": {"rich_text": [{"type": "text", "text": {"content": text}}]},
    }


ADRS: list[tuple[str, str, list[dict], str]] = [
    (
        "🛠️ ADR-12 OpenAI client conventions (Backend)",
        "🛠️",
        [
            para("Status: Accepted (2024-08-14). Owner: Sarah (Backend lead)."),
            h2("Decisions"),
            bullet("All client calls wrapped in retry_wrapper. PR #347 reverted @field_validator after batch-job perf regression. Wrapper stays."),
            bullet("Pydantic models touching OpenAI responses: use legacy @validator only. Never @field_validator (perf path unresolved)."),
            bullet("Pydantic config style: keep `class Config` nested. Do NOT migrate to model_config dict (breaks snake_case JSON aliases)."),
            bullet("Streaming: explicit opt-in (stream=True). Default OFF. Default-on caused INC-203."),
            bullet("Retry policy: tenacity exponential, fixed cap 30s, 5 attempts. No bumps without DevOps signoff."),
        ],
        "backend",
    ),
    (
        "🧪 ADR-15 Embedding pipeline standards (DS)",
        "🧪",
        [
            para("Status: Accepted (2024-07-10). Owner: Iris (DS lead)."),
            h2("Decisions"),
            bullet("Streaming completions REQUIRED for embeddings pipeline. Sync calls cost 4x batch wall-clock."),
            bullet("Sklearn-compatible interface for ML calls. Do not import openai.ChatCompletion directly into pipelines."),
            bullet("Never call sync OpenAI API in batch jobs. See INC-203 postmortem."),
            bullet("Pin OpenAI model versions explicitly. Auto-bump breaks experiment reproducibility."),
        ],
        "ds",
    ),
    (
        "🎨 ADR-18 Frontend API client conventions (UI)",
        "🎨",
        [
            para("Status: Accepted (2024-09-02). Owner: Alice (UI lead)."),
            h2("Decisions"),
            bullet("frontend/src/api-client.ts is auto-generated by openapi-typescript-codegen. Hand-edits forbidden."),
            bullet("jest coverage minimum 80% for api-client and its hooks."),
            bullet("Schema shape changes (camelCase, field rename, removal) need UI sign-off. Spec drift cost a release in Q3."),
            bullet("Data fetching: react-query only. SWR / raw fetch removed in PR #412."),
            bullet("SSE / streaming: use the in-house react-event-source wrapper from frontend/src/lib."),
        ],
        "ui",
    ),
    (
        "🚀 ADR-21 Deployment policy (DevOps)",
        "🚀",
        [
            para("Status: Accepted (2024-11-15). Owner: Grace (DevOps lead)."),
            h2("Decisions"),
            bullet("Dockerfile: multi-stage, slim Debian base. NO alpine — DNS issues in our k8s."),
            bullet("Production binary path: /app/server. Deploy script + healthcheck assume this."),
            bullet("SLO: p99 latency 250ms. Hot-path PRs require benchmark numbers."),
            bullet("k8s pod limits: 128Mi request, 512Mi limit. Bumps require justification."),
            bullet("Image size budget: 250 MB. Current FastAPI ~220 MB. Go rewrite target: <80 MB."),
        ],
        "devops",
    ),
]


def existing_titles_under_parent() -> dict[str, str]:
    """Return {title: page_id} for pages that already exist under teamHQ."""
    out: dict[str, str] = {}
    children = notion("GET", f"/blocks/{PARENT_ID}/children?page_size=100")
    for blk in children.get("results", []):
        if blk.get("type") != "child_page":
            continue
        title = blk.get("child_page", {}).get("title")
        if title:
            out[title] = blk["id"]
    return out


def main() -> int:
    existing = existing_titles_under_parent()
    print(f"Existing children of teamHQ: {len(existing)}")
    for t, pid in existing.items():
        print(f"  - {t}  ({pid})")
    print()

    out_map: dict[str, dict] = {}

    for title, emoji, blocks, team in ADRS:
        if title in existing:
            print(f"  exists: {title}  ({existing[title]})")
            out_map[team] = {"id": existing[title], "url": f"https://www.notion.so/{existing[title].replace('-', '')}"}
            continue

        body = {
            "parent": {"type": "page_id", "page_id": PARENT_ID},
            "icon": {"type": "emoji", "emoji": emoji},
            "properties": {
                "title": {
                    "title": [{"type": "text", "text": {"content": title}}]
                }
            },
            "children": blocks,
        }
        r = notion("POST", "/pages", body)
        if "error" in r:
            print(f"  FAIL: {title}  -> {r}")
            return 1
        url = r.get("url", "")
        page_id = r.get("id", "")
        print(f"  + {title}  ({page_id})")
        print(f"     {url}")
        out_map[team] = {"id": page_id, "url": url}
        time.sleep(0.4)  # rate-limit politeness

    print()
    print("=== ADR map (per team) ===")
    print(json.dumps(out_map, indent=2))

    # Write to .env-friendly file for the agent to consume later
    out_path = Path(__file__).resolve().parent.parent / "agent" / "_notion_adrs.json"
    out_path.write_text(json.dumps(out_map, indent=2))
    print(f"Wrote: {out_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
