"""Create #ui and #devops channels (idempotent — skips if exist) and seed
each w/ realistic team-convention messages. Run alongside the existing
slack_seed.py for #backend + #ds.
"""
from __future__ import annotations

import json
import os
import sys
import time
import urllib.request
from pathlib import Path

env = Path(__file__).resolve().parent.parent / ".env"
if env.exists():
    for line in env.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        k, v = line.split("=", 1)
        os.environ.setdefault(k.strip(), v.strip())

TOKEN = os.environ["SLACK_BOT_TOKEN"]


def call(method: str, body: dict) -> dict:
    req = urllib.request.Request(
        f"https://slack.com/api/{method}",
        data=json.dumps(body).encode(),
        headers={
            "Authorization": f"Bearer {TOKEN}",
            "Content-Type": "application/json; charset=utf-8",
        },
    )
    with urllib.request.urlopen(req, timeout=15) as resp:
        return json.loads(resp.read())


def list_channels() -> dict[str, str]:
    """Return {channel_name: channel_id} for public channels."""
    out: dict[str, str] = {}
    cursor = ""
    while True:
        body = {"types": "public_channel", "limit": 200}
        if cursor:
            body["cursor"] = cursor
        r = call("conversations.list", body)
        for c in r.get("channels", []):
            out[c["name"]] = c["id"]
        cursor = r.get("response_metadata", {}).get("next_cursor", "")
        if not cursor:
            break
    return out


def ensure_channel(name: str, existing: dict[str, str]) -> str:
    if name in existing:
        print(f"  exists: #{name} -> {existing[name]}")
        return existing[name]
    r = call("conversations.create", {"name": name, "is_private": False})
    if not r.get("ok"):
        raise RuntimeError(f"create #{name} failed: {r}")
    cid = r["channel"]["id"]
    print(f"  created: #{name} -> {cid}")
    return cid


def post(channel_id: str, text: str) -> None:
    r = call("chat.postMessage", {"channel": channel_id, "text": text})
    if not r.get("ok"):
        print(f"   post err: {r.get('error')}")


UI_MSGS = [
    "Reminder team — our TS api-client is autogenerated from the FastAPI OpenAPI schema. If backend changes the schema shape, we regen. Don't hand-edit /frontend/src/api-client.ts.",
    "Alice here — we run jest in CI on every PR. Coverage threshold is 80% for /frontend/src/api-client. Don't drop it without a chat.",
    "Heads up: any change that breaks the OpenAPI shape (snake_case→camelCase, removing fields, etc.) needs a UI sign-off. Past spec drift cost us a release in Q3.",
    "We standardized on react-query for data fetching. Don't introduce SWR or fetch-only patterns; we audited and removed them in PR #412.",
    "Streaming responses on the UI — if backend ships SSE, we need 'react-event-source' wrapper from /frontend/src/lib. Don't roll your own.",
]

DEVOPS_MSGS = [
    "Grace here — Dockerfile is multi-stage, slim base. Don't switch to alpine without testing — we hit DNS issues in our k8s last quarter.",
    "Reminder: deploy.sh assumes the binary is at /app/server. If we port from FastAPI to a Go binary, deploy script needs path + healthcheck updates. Coordinate w/ #backend.",
    "SLO budget: p99 latency 250ms. Any change touching request hot path needs benchmark numbers in the PR before merge. No 'I think it's fine' allowed.",
    "Our k8s manifests live in /src/infra/k8s. Resource limits set conservatively (128 Mi req, 512 Mi limit). Don't bump without justification — we've been burned by overcommit.",
    "Image size budget: 250 MB. Current FastAPI build is 220 MB. If we move to Go, target should be <80 MB — that's the cost case for the rewrite.",
]


def main() -> int:
    print("Listing existing channels...")
    existing = list_channels()
    print()

    ui_id = ensure_channel("ui", existing)
    devops_id = ensure_channel("devops", existing)
    print()

    print(f"Seeding #ui ({ui_id}) w/ {len(UI_MSGS)} messages")
    for m in UI_MSGS:
        post(ui_id, m)
        time.sleep(0.3)

    print(f"Seeding #devops ({devops_id}) w/ {len(DEVOPS_MSGS)} messages")
    for m in DEVOPS_MSGS:
        post(devops_id, m)
        time.sleep(0.3)

    print("OK")
    print()
    print("Channels for .env / agent config:")
    print(f"  SLACK_CHANNEL_UI={ui_id}")
    print(f"  SLACK_CHANNEL_DEVOPS={devops_id}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
